apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

namePrefix: staging-

commonLabels:
  app: example-app
  environment: staging

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

images:
- name: nginx
  newTag: "1.21-staging"

configMapGenerator:
- name: staging-config
  literals:
  - DATABASE_URL=postgresql://staging-db:5432/app
  - LOG_LEVEL=info
  - ENVIRONMENT=staging

replicas:
- name: example-deployment
  count: 2
