apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
